# Generated by Django 2.0.1 on 2018-01-31 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
        ('party', '0002_auto_20180131_1525'),
        ('credit', '0002_auto_20180131_1525'),
        ('customer', '0003_auto_20180131_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('job_number', models.CharField(max_length=200)),
                ('job_status', models.CharField(choices=[('active', 'active'), ('complete', 'complete')], max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAccount')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.Credit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobPartyRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.Credit')),
                ('email_contacts', models.ManyToManyField(blank=True, related_name='job_management_jobpartyrole_email_contacts', to='party.EmailContact')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Individual')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_party_roles', to='job_management.Job')),
                ('logical_resources', models.ManyToManyField(blank=True, related_name='job_management_jobpartyrole_logical_resources', to='resource.LogicalResource')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation')),
                ('physical_contacts', models.ManyToManyField(blank=True, related_name='job_management_jobpartyrole_physical_contacts', to='party.PhysicalContact')),
                ('physical_resources', models.ManyToManyField(blank=True, related_name='job_management_jobpartyrole_physical_resources', to='resource.PhysicalResource')),
                ('telephone_numbers', models.ManyToManyField(blank=True, related_name='job_management_jobpartyrole_telephone_numbers', to='party.TelephoneNumber')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
