# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20170815_1129'),
        ('human_resources', '0004_auto_20171117_1411'),
        ('party', '0003_auto_20171117_1411'),
        ('job_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpartyrole',
            name='email_contacts',
            field=models.ManyToManyField(blank=True, related_name='job_management_jobpartyrole_email_contacts', to='party.EmailContact'),
        ),
        migrations.AddField(
            model_name='jobpartyrole',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='human_resources.Identification'),
        ),
        migrations.AddField(
            model_name='jobpartyrole',
            name='logical_resources',
            field=models.ManyToManyField(blank=True, related_name='job_management_jobpartyrole_logical_resources', to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='jobpartyrole',
            name='physical_contacts',
            field=models.ManyToManyField(blank=True, related_name='job_management_jobpartyrole_physical_contacts', to='party.PhysicalContact'),
        ),
        migrations.AddField(
            model_name='jobpartyrole',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='job_management_jobpartyrole_physical_resources', to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='jobpartyrole',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, related_name='job_management_jobpartyrole_telephone_numbers', to='party.TelephoneNumber'),
        ),
    ]
