# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpartyrole',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_party_roles', to='job_management.Job'),
        ),
    ]
