# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpartyrole',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
