# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-12 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchronisationsend',
            name='sync',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='supply_chain.Synchronisations'),
        ),
    ]
