# Generated by Django 2.0.1 on 2018-03-28 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('party', '0004_auto_20180215_0942'),
        ('market', '0001_initial'),
        ('product', '0001_initial'),
        ('sale', '0001_initial'),
        ('location', '0002_auto_20180131_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocktake',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='product.Product'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product.Product'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='channels',
            field=models.ManyToManyField(blank=True, to='sale.SalesChannel'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_offerings', to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='fineline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fineline_offerings', to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offerings', to='product.Product'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='segments',
            field=models.ManyToManyField(blank=True, to='market.MarketSegment'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offerings', to='product.ProductSpecification'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='strategies',
            field=models.ManyToManyField(blank=True, to='market.MarketStrategy'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_department_offerings', to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productassociation',
            name='from_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_products', to='product.Product'),
        ),
        migrations.AddField(
            model_name='productassociation',
            name='to_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_products', to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='associated_products',
            field=models.ManyToManyField(related_name='_product_associated_products_+', through='product.ProductAssociation', to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='bundle',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_products', to='product.Product'),
        ),
    ]
