# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_partner', '0001_initial'),
        ('sale', '0001_initial'),
        ('market', '0001_initial'),
        ('store', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocklevel',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier_partner.Buyer'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='channels',
            field=models.ManyToManyField(blank=True, to='sale.SalesChannel'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='segments',
            field=models.ManyToManyField(blank=True, to='market.MarketSegment'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='strategies',
            field=models.ManyToManyField(blank=True, to='market.MarketStrategy'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier_partner.Supplier'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productassociation',
            name='from_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_products', to='product.Product'),
        ),
        migrations.AddField(
            model_name='productassociation',
            name='to_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_products', to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='associated_products',
            field=models.ManyToManyField(related_name='_product_associated_products_+', through='product.ProductAssociation', to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='bundle',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.ProductCategory'),
        ),
    ]
