# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('product', '0002_productoffering_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffering',
            name='segments',
            field=models.ManyToManyField(blank=True, to='market.MarketSegment'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='status',
            field=models.CharField(default='Active', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoffering',
            name='strategies',
            field=models.ManyToManyField(blank=True, to='market.MarketStrategy'),
        ),
    ]
