# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170620_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='productoffering',
            options={'ordering': ['id']},
        ),
    ]
