# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170811_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('association_type', models.CharField(choices=[('cross-selling', 'cross-selling'), ('other', 'other')], default='cross-selling', max_length=200)),
                ('rank', models.IntegerField(default=0)),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_products', to='product.Product')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_products', to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='associated_products',
            field=models.ManyToManyField(related_name='_product_associated_products_+', through='product.ProductAssociation', to='product.Product'),
        ),
    ]
