# Generated by Django 2.0.1 on 2018-02-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180131_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exclusive',
            field=models.CharField(blank=True, choices=[('RE', 'Retail Exclusive'), ('E', 'Exclusive'), ('P', 'Proprietary'), ('BTR', 'Better'), ('BES', 'Best'), ('BTY', 'BTY')], max_length=50),
        ),
    ]
