# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171214_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='core_abc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='core_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='first_sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='impulse_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='key_value_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_products', to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_code',
            field=models.CharField(default='G', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='carton_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='quantity_break1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='quantity_break2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='quantity_price1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='quantity_price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='reccomended_markup',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
