# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_remove_retailchannel_product_offerings'),
        ('product', '0003_auto_20170602_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffering',
            name='channels',
            field=models.ManyToManyField(blank=True, to='sale.RetailChannel'),
        ),
    ]
