# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170620_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier_code',
        ),
        migrations.AddField(
            model_name='productoffering',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('each', 'each'), ('kg', 'kg'), ('meter', 'meter')], default='each', max_length=200),
        ),
    ]
