# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170818_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='associated_products',
            field=models.ManyToManyField(related_name='associated_to', through='product.ProductAssociation', to='product.Product'),
        ),
    ]
