# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('location', '0002_auto_20170811_1315'),
        ('product', '0003_auto_20170907_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(choices=[('each', 'each'), ('kg', 'kg'), ('meter', 'meter')], default='each', max_length=200)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=8)),
                ('average', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('reorder_minimum', models.DecimalField(decimal_places=4, max_digits=8)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='product.Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStockTake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('unit_of_measure', models.CharField(choices=[('each', 'each'), ('kg', 'kg'), ('meter', 'meter')], default='each', max_length=200)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=8)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('product_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_takes', to='product.ProductStock')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
        migrations.RemoveField(
            model_name='productstocklevel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='productstocklevel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productstocklevel',
            name='store',
        ),
        migrations.DeleteModel(
            name='ProductStockLevel',
        ),
    ]
