# Generated by Django 2.0.1 on 2018-02-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180220_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('exiting', 'exiting'), ('pending', 'pending'), ('suspended', 'suspended')], default='active', max_length=50),
        ),
    ]
