# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_auto_20171214_1623'),
        ('product', '0003_auto_20171215_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='merch_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='forecast.MerchWeek'),
        ),
    ]
