# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productstock_merch_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
