# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180111_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffering',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier_sku',
            field=models.CharField(max_length=200),
        ),
    ]
