# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170620_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='level',
            field=models.CharField(choices=[('department', 'department'), ('subdepartment', 'subdepartment'), ('fineline', 'fineline')], max_length=200),
        ),
        migrations.AlterField(
            model_name='productoffering',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=200),
        ),
    ]
