# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productoffering_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOfferingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categories', models.ManyToManyField(blank=True, to='product.ProductCategory')),
                ('promotions', models.ManyToManyField(blank=True, to='product.Promotion')),
            ],
        ),
        migrations.AddField(
            model_name='productoffering',
            name='prices',
            field=models.ManyToManyField(blank=True, to='product.ProductOfferingPrice'),
        ),
    ]
