# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_auto_20170811_1315'),
        ('product', '0004_auto_20170908_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstocktake',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.Staff'),
        ),
    ]
