# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productstock_retail_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='merch_week',
        ),
        migrations.AddField(
            model_name='productstock',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
