# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20170602_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productofferingprice',
            name='promotions',
        ),
        migrations.AddField(
            model_name='productofferingprice',
            name='product_offering',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.ProductOffering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productofferingprice',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Promotion'),
        ),
    ]
