# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productstocktake_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffering',
            name='average_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='reccomended_retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
