# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
        ('product', '0006_auto_20170908_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_offerings', to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='fineline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fineline_offerings', to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_department_offerings', to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='type',
            field=models.CharField(choices=[('standard', 'standard'), ('fractional', 'fractional'), ('kit', 'kit')], default='standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoffering',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
