# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20171218_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='reorder_minimum',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
