# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('party', '0006_auto_20170619_1304'),
        ('product', '0006_auto_20170602_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=8)),
                ('average', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.AbsoluteLocalLocation')),
            ],
        ),
        migrations.RemoveField(
            model_name='productoffering',
            name='prices',
        ),
        migrations.AddField(
            model_name='productoffering',
            name='unit_of_measure',
            field=models.CharField(default='Each', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productofferingprice',
            name='product_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offering_prices', to='product.ProductOffering'),
        ),
        migrations.AddField(
            model_name='productstocklevel',
            name='product_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductOffering'),
        ),
        migrations.AddField(
            model_name='productstocklevel',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
    ]
