# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20171218_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='level',
            field=models.CharField(choices=[('division', 'division'), ('category', 'category'), ('department', 'department'), ('sub_department', 'sub_department'), ('fineline', 'fineline')], max_length=200),
        ),
    ]
