# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20171002_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='level',
            field=models.CharField(choices=[('department', 'department'), ('sub_department', 'sub_department'), ('fineline', 'fineline')], max_length=200),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
