# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-02 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20171002_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_name', models.CharField(blank=True, max_length=50, null=True)),
                ('colour_value', models.CharField(blank=True, max_length=50, null=True)),
                ('size_name', models.CharField(blank=True, max_length=50, null=True)),
                ('size_value', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='product.Product'),
        ),
        migrations.AddField(
            model_name='productoffering',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offerings', to='product.ProductSpecification'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='product.ProductSpecification'),
        ),
    ]
