version: '2'
services:
    cbeapp:
        image: semprini/cbe-retail
        environment:
            DBENGINE: postgresql
            DBHOST: cbedb
            DBNAME: cbe
            DBPASSWORD: docker
            DBUSER: docker
        ports:
            - "8000:8000"
        depends_on:
            - cbedb
    cbedb:
        image: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_USER: docker
            POSTGRES_DB: cbe
    cbemq:
        image: rabbitmq:3-management
        ports:
            - "8080:15672"

volumes:
    db-data:
