version: '2'
services:
    cbe_microservice_loyalty:
        build: retail/loyalty/microservices/caluclate_loyalty_transaction/
        depends_on:
            - cbeapp
            - cbemq
    cbeapp:
        image: semprini/cbe-retail
        environment:
            DBENGINE: postgresql
            DBHOST: cbedb
            DBNAME: cbe
            DBPASSWORD: docker
            DBUSER: docker
            MQHOST: cbemq
            MQUSER: guest
            MQPASSWORD: guest
        depends_on:
            - cbedb
            - cbemq
        ports:
            - "8000:8000"
    cbedb:
        image: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_USER: docker
            POSTGRES_DB: cbe
    cbemq:
        image: rabbitmq:3-management
        ports:
            - "8080:15672"

volumes:
    db-data:
