# Generated by Django 2.0.1 on 2018-02-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('customer', '0005_auto_20180215_0942'),
        ('order', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductOffering'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.Promotion'),
        ),
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAccount'),
        ),
    ]
