# Generated by Django 2.0.1 on 2018-02-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0002_auto_20180227_1212'),
        ('customer', '0005_auto_20180215_0942'),
        ('order', '0002_auto_20180227_1212'),
        ('party', '0004_auto_20180215_0942'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.SalesChannel'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.PriceCalculation'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.PriceChannel'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.Promotion'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
    ]
