# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20170721_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_offering',
        ),
    ]
