# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0006_auto_20170908_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merch_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_forecasts', to='forecast.MerchWeek')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_forecasts', to='product.Product')),
            ],
        ),
    ]
