# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productforecast',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_forecasts', to='product.Product'),
        ),
    ]
