# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171214_1254'),
        ('forecast', '0002_productforecast_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateField()),
                ('calendar_date_txt', models.CharField(max_length=100)),
                ('calendar_week_end', models.DateField()),
                ('calendar_week_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductStockWeekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='merchweek',
            old_name='end',
            new_name='calendar_end',
        ),
        migrations.RemoveField(
            model_name='merchweek',
            name='start',
        ),
        migrations.AddField(
            model_name='merchweek',
            name='calendar_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchweek',
            name='calendar_week_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchweek',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchweek',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchweek',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='productstockweekly',
            name='merch_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merch_weeks', to='forecast.MerchWeek'),
        ),
        migrations.AddField(
            model_name='productstockweekly',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_weekly', to='product.Product'),
        ),
        migrations.AddField(
            model_name='productstockweekly',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_weekly', to='forecast.MerchWeek'),
        ),
        migrations.AddField(
            model_name='merchdate',
            name='merch_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merch_dates', to='forecast.MerchWeek'),
        ),
    ]
