# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('product', '0001_initial'),
        ('forecast', '0002_productsaleweek_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsaleweek',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_weekly', to='store.Store'),
        ),
        migrations.AddField(
            model_name='productforecast',
            name='merch_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_forecasts', to='forecast.MerchWeek'),
        ),
        migrations.AddField(
            model_name='productforecast',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_forecasts', to='product.Product'),
        ),
        migrations.AddField(
            model_name='merchdate',
            name='merch_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merch_dates', to='forecast.MerchWeek'),
        ),
    ]
