# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20171218_1227'),
        ('forecast', '0004_auto_20171218_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSaleWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('on_hand', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('on_order', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('merch_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merch_weeks', to='forecast.MerchWeek')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_weekly', to='product.Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_weekly', to='forecast.MerchWeek')),
            ],
        ),
        migrations.RemoveField(
            model_name='salesweekly',
            name='merch_week',
        ),
        migrations.RemoveField(
            model_name='salesweekly',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesweekly',
            name='store',
        ),
        migrations.DeleteModel(
            name='SalesWeekly',
        ),
    ]
