# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_auto_20171220_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsaleweek',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
