# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_auto_20171218_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsaleweek',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_weekly', to='store.Store'),
        ),
    ]
