# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_auto_20171218_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsaleweek',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
