# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180111_1406'),
        ('forecast', '0006_auto_20180112_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSaleWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('store_count', models.IntegerField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('on_hand', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('on_order', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('store_stock_count', models.IntegerField()),
                ('store_sales_count', models.IntegerField()),
                ('merch_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sales_weekly_merch_weeks', to='forecast.MerchWeek')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales_weekly', to='product.Product')),
            ],
        ),
    ]
