# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_productsaleweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsaleweek',
            name='product_txtid',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeproductsaleweek',
            name='product_txtid',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsaleweek',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sales_weekly', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='storeproductsaleweek',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_product_sales_weekly', to='product.Product'),
        ),
    ]
