# Generated by Django 2.0.1 on 2018-01-31 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
        ('party', '0002_auto_20180131_1525'),
        ('physical_object', '0001_initial'),
        ('location', '0002_auto_20180131_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('enterprise_id', models.IntegerField(null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('store_type', models.CharField(blank=True, choices=[('mitre 10', 'mitre 10'), ('mega', 'mega'), ('hammer', 'hammer'), ('trade', 'trade')], max_length=100, null=True)),
                ('store_class', models.CharField(blank=True, choices=[('mega-1', 'mega-1'), ('mega-2', 'mega-2'), ('mega-3', 'mega-3'), ('mega-r', 'mega-r'), ('mitre10-small', 'mitre10-small'), ('mitre10-medium', 'mitre10-medium'), ('mitre10-large', 'mitre10-large'), ('trade', 'trade')], max_length=100, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('buildings', models.ManyToManyField(related_name='store', to='physical_object.Structure')),
                ('email_contacts', models.ManyToManyField(blank=True, related_name='store_store_email_contacts', to='party.EmailContact')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Individual')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
                ('logical_resources', models.ManyToManyField(blank=True, related_name='store_store_logical_resources', to='resource.LogicalResource')),
                ('national_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_national_areas', to='location.GeographicArea')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation')),
                ('physical_contacts', models.ManyToManyField(blank=True, related_name='store_store_physical_contacts', to='party.PhysicalContact')),
                ('physical_resources', models.ManyToManyField(blank=True, related_name='store_store_physical_resources', to='resource.PhysicalResource')),
                ('retail_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_retail_areas', to='location.GeographicArea')),
                ('telephone_numbers', models.ManyToManyField(blank=True, related_name='store_store_telephone_numbers', to='party.TelephoneNumber')),
                ('trade_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_trade_areas', to='location.GeographicArea')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
