# Generated by Django 2.0.1 on 2018-02-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='enterprise_id',
            field=models.IntegerField(unique=True),
        ),
    ]
