# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20171222_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_class',
            field=models.CharField(blank=True, choices=[('mitre 10', 'mitre 10'), ('mega', 'mega'), ('hammer', 'hammer')], max_length=100, null=True),
        ),
    ]
