# Generated by Django 2.0.1 on 2018-02-14 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180212_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
