# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20180119_0903'),
        ('store', '0003_auto_20171222_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_class',
            new_name='store_type',
        ),
        migrations.AddField(
            model_name='store',
            name='national_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_national_areas', to='location.GeographicArea'),
        ),
        migrations.AddField(
            model_name='store',
            name='retail_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_retail_areas', to='location.GeographicArea'),
        ),
        migrations.AddField(
            model_name='store',
            name='trade_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_trade_areas', to='location.GeographicArea'),
        ),
    ]
