# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180119_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_class',
            field=models.CharField(blank=True, choices=[('mega-1', 'mega-1'), ('mega-2', 'mega-2'), ('mega-3', 'mega-3'), ('mega-r', 'mega-r'), ('mitre10-small', 'mitre10-small'), ('mitre10-medium', 'mitre10-medium'), ('mitre10-large', 'mitre10-large'), ('trade', 'trade')], max_length=100, null=True),
        ),
    ]
