# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_store_store_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='enterprise_id',
            field=models.IntegerField(null=True),
        ),
    ]
