# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_object', '0001_initial'),
        ('store', '0006_store_enterprise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='buildings',
            field=models.ManyToManyField(related_name='store', to='physical_object.Structure'),
        ),
    ]
