# Generated by Django 2.0.1 on 2018-01-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_store_buildings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(blank=True, choices=[('mitre 10', 'mitre 10'), ('mega', 'mega'), ('hammer', 'hammer'), ('trade', 'trade')], max_length=100, null=True),
        ),
    ]
