# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0002_auto_20171214_1248'),
        ('resource', '0001_initial'),
        ('sale', '0001_initial'),
        ('store', '0001_initial'),
        ('credit', '0002_auto_20171214_1248'),
        ('customer', '0003_auto_20171214_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
        migrations.AddField(
            model_name='sale',
            name='till',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='sale',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAccount'),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.Credit'),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='email_contacts',
            field=models.ManyToManyField(blank=True, related_name='sale_purchaser_email_contacts', to='party.EmailContact'),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Individual'),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='logical_resources',
            field=models.ManyToManyField(blank=True, related_name='sale_purchaser_logical_resources', to='resource.LogicalResource'),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='physical_contacts',
            field=models.ManyToManyField(blank=True, related_name='sale_purchaser_physical_contacts', to='party.PhysicalContact'),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='physical_resources',
            field=models.ManyToManyField(blank=True, related_name='sale_purchaser_physical_resources', to='resource.PhysicalResource'),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, related_name='sale_purchaser_telephone_numbers', to='party.TelephoneNumber'),
        ),
    ]
