# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170602_1134'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailchannel',
            name='product_offerings',
            field=models.ManyToManyField(blank=True, to='product.ProductOffering'),
        ),
    ]
