# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_auto_20170619_1304'),
        ('sale', '0002_auto_20170620_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='store',
            new_name='location',
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_of_measure',
            field=models.CharField(choices=[('each', 'each'), ('kg', 'kg'), ('meter', 'meter')], default='each', max_length=200),
        ),
    ]
