# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_auto_20170811_1434'),
        ('sale', '0002_auto_20170811_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='credit_balance_events',
            field=models.ManyToManyField(blank=True, null=True, to='credit.CreditBalanceEvent'),
        ),
    ]
