# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170824_1659'),
        ('sale', '0002_auto_20170824_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductOffering'),
        ),
    ]
