# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_retailchannel_product_offerings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailchannel',
            name='product_offerings',
        ),
    ]
