# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20170907_1604'),
        ('sale', '0002_auto_20170907_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='product_offering_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pricing.ProductOfferingPrice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product_offering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.ProductOffering'),
            preserve_default=False,
        ),
    ]
