# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20170717_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='unit_of_measure',
            field=models.CharField(choices=[('each', 'each'), ('kg', 'kg'), ('metre', 'metre')], default='each', max_length=200),
        ),
    ]
