# Generated by Django 2.0.1 on 2018-02-14 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20180131_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaser',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
