# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_sale_credit_balance_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='credit_balance_events',
            field=models.ManyToManyField(blank=True, to='credit.CreditBalanceEvent'),
        ),
    ]
