# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20170808_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaser',
            name='identification',
        ),
        migrations.AddField(
            model_name='purchaser',
            name='transation_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
