# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_auto_20171117_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaser',
            name='identifiers',
        ),
    ]
