# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
        ('sale', '0001_initial'),
        ('customer', '0002_auto_20170721_1450'),
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditbalanceevent',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='creditalert',
            name='credit_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='creditalert',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='creditalert',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.CreditProfile'),
        ),
    ]
