# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditbalanceevent',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance_events', to='sale.Sale'),
        ),
    ]
