# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20170721_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditprofile',
            name='date',
        ),
        migrations.AddField(
            model_name='creditprofile',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
