# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
        ('store', '0001_initial'),
        ('credit', '0002_creditbalanceevent_sale'),
        ('customer', '0003_auto_20170804_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditbalanceevent',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
        migrations.AddField(
            model_name='creditalert',
            name='credit_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='creditalert',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='creditalert',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.CreditProfile'),
        ),
    ]
