# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_auto_20170724_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditbalanceevent',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance_events', to='sale.Sale'),
        ),
    ]
