# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0002_auto_20170824_1659'),
        ('sale', '0001_initial'),
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytransaction',
            name='items',
            field=models.ManyToManyField(blank=True, to='sale.SaleItem'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.Promotion'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loyalty.LoyaltyScheme'),
        ),
    ]
