# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_auto_20170907_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytransaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='sale.Sale'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loyalty.LoyaltyScheme'),
            preserve_default=False,
        ),
    ]
