# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loyalty', '0002_loyaltytransaction_promotion'),
        ('party', '0003_auto_20171214_1743'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='sale_items',
            field=models.ManyToManyField(blank=True, to='sale.SaleItem'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.LoyaltyScheme'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
        ),
    ]
