# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
        ('loyalty', '0003_auto_20170910_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytransaction',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation'),
            preserve_default=False,
        ),
    ]
