# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_loyaltytransaction_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltytransaction',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='identification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='human_resources.Identification'),
            preserve_default=False,
        ),
    ]
