# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_auto_20170913_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyscheme',
            name='loyalty_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
