# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_receivable', '0001_initial'),
        ('loyalty', '0006_loyaltyscheme_loyalty_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyaltytransaction',
            old_name='items',
            new_name='sale_items',
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='accounts_receivable.CustomerPayment'),
        ),
    ]
