# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('customer', '0002_auto_20170811_1315'),
        ('party', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='customers',
            field=models.ManyToManyField(blank=True, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='product_offerings',
            field=models.ManyToManyField(blank=True, to='product.ProductOffering'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='stores',
            field=models.ManyToManyField(blank=True, to='party.Organisation'),
        ),
        migrations.AddField(
            model_name='productofferingprice',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productofferingprice',
            name='product_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offering_prices', to='product.ProductOffering'),
        ),
        migrations.AddField(
            model_name='productofferingprice',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offering_prices', to='pricing.Promotion'),
        ),
        migrations.AddField(
            model_name='pricecalculation',
            name='price_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.PriceChannel'),
        ),
    ]
