# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0002_auto_20171214_1254'),
        ('order', '0004_order_store'),
        ('store', '0001_initial'),
        ('product', '0001_initial'),
        ('customer', '0003_auto_20171214_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='stores',
            field=models.ManyToManyField(blank=True, to='store.Store'),
        ),
        migrations.AddField(
            model_name='productofferingprice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offering_prices', to='customer.CustomerAccount'),
        ),
        migrations.AddField(
            model_name='productofferingprice',
            name='calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offering_prices', to='pricing.PriceCalculation'),
        ),
        migrations.AddField(
            model_name='productofferingprice',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productofferingprice',
            name='product_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offering_prices', to='product.ProductOffering'),
        ),
        migrations.AddField(
            model_name='productofferingprice',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offering_prices', to='pricing.Promotion'),
        ),
        migrations.AddField(
            model_name='productofferingprice',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offering_prices', to='order.Quote'),
        ),
        migrations.AddField(
            model_name='pricecalculation',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='customer.CustomerAccount'),
        ),
        migrations.AddField(
            model_name='pricecalculation',
            name='categories',
            field=models.ManyToManyField(blank=True, to='product.ProductCategory'),
        ),
        migrations.AddField(
            model_name='pricecalculation',
            name='customers',
            field=models.ManyToManyField(blank=True, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='pricecalculation',
            name='price_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.PriceChannel'),
        ),
        migrations.AddField(
            model_name='pricecalculation',
            name='product_offerings',
            field=models.ManyToManyField(blank=True, to='product.ProductOffering'),
        ),
        migrations.AddField(
            model_name='pricecalculation',
            name='stores',
            field=models.ManyToManyField(blank=True, to='store.Store'),
        ),
    ]
