# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20170721_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='products',
            new_name='product_offerings',
        ),
    ]
