# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_auto_20170921_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofferingprice',
            name='calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_offering_prices', to='pricing.PriceCalculation'),
        ),
    ]
