# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AllocationBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active'), ('due', 'due'), ('disputed', 'disputed'), ('closed', 'closed')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjusted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rebated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disputed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allocated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBillingCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('billing_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_due', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBillSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DisputeBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RebateBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('home_margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('satellite_margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptionbillitems', to='customer_bill.CustomerBill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
