# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('customer', '0005_auto_20170619_1304'),
        ('party', '0006_auto_20170619_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('account', 'account'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdjustmentBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('account', 'account'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('account', 'account'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active'), ('due', 'due'), ('disputed', 'disputed'), ('closed', 'closed')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjusted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rebated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disputed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allocated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAccount')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBillingCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('billing_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_due', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAccount')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBillSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerAccount')),
                ('billing_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_bill.CustomerBillingCycle')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.AbsoluteLocalLocation')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='DisputeBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('account', 'account'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_bill.CustomerBill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RebateBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('account', 'account'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_bill.CustomerBill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('account', 'account'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_bill.CustomerBill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('account', 'account'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_bill.CustomerBill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerbill',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_bill.CustomerBillSpecification'),
        ),
        migrations.AddField(
            model_name='allocationbillitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_bill.CustomerBill'),
        ),
        migrations.AddField(
            model_name='adjustmentbillitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_bill.CustomerBill'),
        ),
        migrations.AddField(
            model_name='accountbillitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_bill.CustomerBill'),
        ),
    ]
