# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbill',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
