# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbillitem',
            old_name='type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='adjustmentbillitem',
            old_name='type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='allocationbillitem',
            old_name='type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='disputebillitem',
            old_name='type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='rebatebillitem',
            old_name='type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='servicebillitem',
            old_name='type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='subscriptionbillitem',
            old_name='type',
            new_name='item_type',
        ),
    ]
