# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbillitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='adjustmentbillitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='allocationbillitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='customerbill',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='customerbillingcycle',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='customerbillspecification',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='disputebillitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rebatebillitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='servicebillitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subscriptionbillitem',
            options={'ordering': ['id']},
        ),
    ]
