# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
        ('customer_bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionbillitem',
            name='sale_events',
            field=models.ManyToManyField(blank=True, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicecharges', to='customer_bill.CustomerBill'),
        ),
    ]
