# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_receivable', '0003_customerpayment_vendor'),
        ('customer_bill', '0002_auto_20171219_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationbillitem',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts_receivable.CustomerPayment'),
            preserve_default=False,
        ),
    ]
