# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20170811_1439'),
        ('customer_bill', '0002_auto_20170823_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('account', 'account'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_bill.CustomerBill')),
                ('sale_events', models.ManyToManyField(blank=True, to='sale.Sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='accountbillitem',
            name='sale_events',
            field=models.ManyToManyField(blank=True, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='adjustmentbillitem',
            name='sale_events',
            field=models.ManyToManyField(blank=True, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='allocationbillitem',
            name='sale_events',
            field=models.ManyToManyField(blank=True, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='disputebillitem',
            name='sale_events',
            field=models.ManyToManyField(blank=True, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='rebatebillitem',
            name='sale_events',
            field=models.ManyToManyField(blank=True, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='servicebillitem',
            name='sale_events',
            field=models.ManyToManyField(blank=True, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='subscriptionbillitem',
            name='sale_events',
            field=models.ManyToManyField(blank=True, to='sale.Sale'),
        ),
    ]
