# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
        ('sale', '0002_auto_20170824_1659'),
        ('customer_bill', '0002_auto_20170824_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareableMargin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('home_margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('satellite_margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareablemargins', to='customer_bill.CustomerBill')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale')),
                ('satellite_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.Organisation')),
            ],
        ),
        migrations.AlterField(
            model_name='accountbillitem',
            name='item_type',
            field=models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100),
        ),
        migrations.AlterField(
            model_name='adjustmentbillitem',
            name='item_type',
            field=models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100),
        ),
        migrations.AlterField(
            model_name='allocationbillitem',
            name='item_type',
            field=models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100),
        ),
        migrations.AlterField(
            model_name='disputebillitem',
            name='item_type',
            field=models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobbillitem',
            name='item_type',
            field=models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rebatebillitem',
            name='item_type',
            field=models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicebillitem',
            name='item_type',
            field=models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionbillitem',
            name='item_type',
            field=models.CharField(choices=[('account', 'account'), ('job', 'job'), ('subscription', 'subscription'), ('service', 'service'), ('rebate', 'rebate'), ('allocation', 'allocation'), ('adjustment', 'adjustment'), ('dispute', 'dispute')], max_length=100),
        ),
    ]
