# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_bill', '0003_auto_20170907_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecharge',
            name='home_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_service_charges', to='party.Organisation'),
        ),
        migrations.AlterField(
            model_name='servicecharge',
            name='satellite_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satellite_service_charges', to='party.Organisation'),
        ),
    ]
