# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20170824_1659'),
        ('party', '0001_initial'),
        ('customer_bill', '0003_auto_20170825_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('home_margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('satellite_margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicecharges', to='customer_bill.CustomerBill')),
                ('home_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_service_charges', to='party.Organisation')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale')),
                ('satellite_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satellite_service_charges', to='party.Organisation')),
                ('service_bill_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicecharges', to='customer_bill.ServiceBillItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='shareablemargin',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='shareablemargin',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='shareablemargin',
            name='satellite_organisation',
        ),
        migrations.DeleteModel(
            name='ShareableMargin',
        ),
    ]
