# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20170910_0100'),
        ('customer_bill', '0004_auto_20170913_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecharge',
            name='sale',
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='sales',
            field=models.ManyToManyField(blank=True, to='sale.Sale'),
        ),
    ]
