# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20170824_1650'),
        ('store', '0001_initial'),
        ('customer_bill', '0004_auto_20170828_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbillspecification',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='servicecharge',
            name='home_organisation',
        ),
        migrations.RemoveField(
            model_name='servicecharge',
            name='satellite_organisation',
        ),
        migrations.AddField(
            model_name='customerbillspecification',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='home_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_service_charges', to='store.Store'),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='satellite_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satellite_service_charges', to='store.Store'),
        ),
    ]
