# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0001_initial'),
        ('customer_bill', '0006_customerbill_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbillitem',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_management.Job'),
            preserve_default=False,
        ),
    ]
